version: '3.8'

services:
    jibri:
        image: theun/jibri:latest
        restart: ${RESTART_POLICY}
        build:
            context: ./docker-jitsi-meet/jibri
            dockerfile: Dockerfile
        volumes:
            - ${CONFIG}/jibri:/config:Z
            - /dev/shm:/dev/shm
        command: /wait-for-it.sh -t 0 prosody:5222 -- /init
        environment:
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - XMPP_SERVER
            - XMPP_DOMAIN
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_BREWERY_MUC
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDING_DIR
            - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
            - JIBRI_STRIP_DOMAIN_JID
            - JIBRI_LOGS_DIR
            - TZ
            - PUBLIC_URL
            - RECORDING_DOWNLOAD_BASE
            - RECORDING_RETETION_DAYS
            - NOREPLY_MAIL
            - SMTP_SERVER
            - DISPLAY=:0
        depends_on:
            - jicofo
        networks:
            meet.jitsi:

    storage:
        image: theun/storage:latest
        restart: ${RESTART_POLICY}
        build:
            context: ./docker-jitsi-meet/storage
            dockerfile: Dockerfile
        volumes:
            - ${CONFIG}/storage:/recordings:z
        environment:
            - RECORDING_RETETION_DAYS
        networks:
            meet.jitsi:
