version: '3.8'

services:
    # Auth Frontend
    vmfront:
        image: theun/vmfront:latest
        env_file: .env
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # Auth API Backend
    vmapi:
        image: theun/vmapi:latest
        env_file: .env
        command: /vmeeting-api/wait-for-it.sh -t 0 mongo:27017 -- nodemon -x "node app.js || (sleep 10; touch app.js)"
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    mongo:
        image: theun/mongo:latest
        env_file: .env
        volumes:
            - ~/.jitsi-meet-cfg/mongo:/data/db
        # We use WiredTiger in all environments. In development environments we use small files
        # to conserve disk space, and disable the journal for a minor performance gain.
        # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
        command: mongod --smallfiles --nojournal --storageEngine wiredTiger
        networks:
            jitsi_meet:
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # Monitoring stack
    influxdb:
        image: influxdb:1.8
        networks:
            jitsi_meet:
        volumes:
            - ~/.jitsi-meet-cfg/influxdb:/var/lib/influxdb
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    grafana:
        image: theun/grafana:latest
        env_file: .env
        user: "0"
        volumes:
            -  ~/.jitsi-meet-cfg/grafana:/var/lib/grafana
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    web:
        image: theun/web:latest
        env_file: .env
        volumes:
            - ~/.jitsi-meet-cfg/web:/config
            - ~/.jitsi-meet-cfg/web/letsencrypt:/etc/letsencrypt
            - ~/.jitsi-meet-cfg/transcripts:/usr/share/jitsi-meet/transcripts
            - ~/.jitsi-meet-cfg/storage:/recordings
        ports:
            - '80:80'
            - '443:443'
        networks:
            jitsi_meet:
                aliases:
                    - meet.jitsi
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # storage must be in the same node with web
    storage:
        image: theun/storage:latest
        volumes:
            - ~/.jitsi-meet-cfg/storage:/recordings
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # XMPP server
    prosody:
        image: theun/prosody:latest
        env_file: .env
        networks:
            jitsi_meet:
                aliases:
                    - xmpp.meet.jitsi
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # Focus component
    jicofo:
        image: theun/jicofo:latest
        env_file: .env
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"

    # Video bridge
    jvb:
        image: theun/jvb:latest
        env_file: .env
        ports:
            - target: 10000
              published: 10000
              protocol: udp
              mode: host
            - target: 4443
              published: 4443
              protocol: tcp
              mode: host
        volumes:
            - /sys:/rootfs/sys:ro
            - /proc:/rootfs/proc:ro
            - /etc:/rootfs/etc:ro
        environment:
            - HOST_PROC=/rootfs/proc
            - HOST_SYS=/rootfs/sys
            - HOST_ETC=/rootfs/etc
        networks:
            jitsi_meet:
        deploy:
            # we need exactly one jvb for each host
            mode: global

    jibri:
        image: theun/jibri:latest
        env_file: .env
        command: /wait-for-it.sh -t 0 prosody:5222 -- /init
        environment:
            - DISPLAY=:0
        volumes:
            - /dev/shm:/dev/shm
        networks:
            jitsi_meet:
        deploy:
            replicas: 12

networks:
    jitsi_meet:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
